
nickname:
  - my_miner
region:
  - asia
url:
  - localhost:7001
capacity:
  - 1024000000
unit_price:
  - 100
meta_path:
  - /ipse-miner/meta
ipfs_url:
  - localhost:5001
chain_url:
  - ws://localhost:9944